inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

require: rubocop-rspec

# Override Setting
AllCops:
  TargetRubyVersion: 3.2
  
# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: around

# Two spaces, no tabs (for indentation).
Layout/IndentationWidth:
  Enabled: true
  AllowedPatterns: ['^\s*private', '^\s*protected']
